### ISSUE TITLE
Username and Password Constraints

### ISSUE THREAD

**Issue by snaramirez872** [ppauliuchenka02/bandgeeks-news-app#16]
Username is a string with at least 8 characters **(no spaces)**
Password should be at least 8 characters long **(at least 1 upper case letter, at least 1 lower case letter, and must contain at least 1 special character)**

**Comment by ppauliuchenka02** [comment]
o	Requirement 2
	The user name shall be a string at least 8 character long
	The user name shall not include any spaces
	The UX shall automatically trim leading and trailing spaces
o	Requirement 3
	The password shall not include any spaces
	The password shall be at least 8 characters long
	The UX shall automatically trim leading and trailing spaces
	The password must contain at least one upper case letter
	The password must contain at least one lower case letter
	The password must contain at least one character that is not a letter

**Comment by snaramirez872** [comment]
Just finished with this, will open a pull request into sprint-1 soon
