### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by ppauliuchenka02** [ppauliuchenka02/bandgeeks-news-app#17]
- Update your database schema
- If using an RDBMS
- Table: user
–	Column: userid integer – primary key unique sequence number
–	Column: username string – user name from sign up
–	Column: password string – password from sign up
–	Column: general boolean – true if the user has chosen General
–	Column: business boolean – true if the user has chosen Business
–	Column: entertainment boolean – true if the user has chosen Entertainment
–	Column: health boolean – true if the user has chosen Health
–	Column: science boolean – true if the user has chosen Science
–	Column: sports boolean – true if the user has chosen Sports
–	Column: technology boolean – true if the user has chosen Technology
- Note. This is (still) not best practice, nor normal form

**Comment by snaramirez872** [comment]
Database stuff is almost done, I just have to help out Carlos make and run the tests

**Comment by cdb24** [comment]
database entries have been created and tests written and passed, closing this issue
