### ISSUE TITLE
fix settings page AGAIN

### ISSUE THREAD

**Issue by ChowChowSonic** [ppauliuchenka02/bandgeeks-news-app#43]

**Comment by ChowChowSonic** [comment]
Everything works fine on my laptop, but everybody else says that theirs only works once. I'm not going to do anything here; instead we can present on my laptop for the final sprint.

**Comment by ppauliuchenka02** [comment]
it works on my end as well but I have to refresh my page before changing and saving preferences.

**Comment by ppauliuchenka02** [comment]
was fixed!
